config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: [:new]

  get '/register', to: 'chefs#new'

  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

end

app/models/chef.rb
class Chef < ActiveRecord::Base
  has_many :recipes
  has_many :likes
  before_save { self.email = email.downcase }
  validates :chefname, presence: true, length: { minimum: 3, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe

  validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :chef
  has_many :likes
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum: 5, maximum: 100 }
  validates :description, presence: true
  mount_uploader :picture, PictureUploader
  validate :picture_size

  default_scope -> { order(updated_at: :desc) }

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "Should be less than 5MB")
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :find_chef, only: [:edit, :update, :show]
  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 5)
  end

  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      flash[:success] = "Your account has been created succesfully!"
      session[:chef_id] = @chef.id
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @chef.update(chef_params)
      flash[:success] = "Your profile has been updated succesfully!"
      redirect_to recipes_path #TODO change to chef show page
    else
      render 'edit'
    end
  end

  def show
    @recipes = @chef.recipes.paginate(page: params[:page], per_page: 5)
  end

  def destroy
  end

  private
    def find_chef
      @chef = Chef.find(params[:id])
    end

    def chef_params
      params.require(:chef).permit(:chefname, :email, :password)
    end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new
  end

  def create
    chef = Chef.find_by(email: params[:email])
    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:success] = "Successfully signed in. Welcome #{chef.chefname}"
      redirect_to recipes_path
    else
      flash.now[:danger] = "Incorrect email or password."
      render 'new'
    end
  end

  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have successfully been signed out."
    redirect_to root_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only: [:show, :edit, :update, :like]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 2)
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = Chef.find(2)
    if @recipe.save
      flash[:success] = "Your recipe was saved succesfully!"
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Your recipe was succesfully updated!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def like
    like = Like.create(like: params[:like], chef: Chef.first, recipe: @recipe)
    if like.valid?
      flash[:success] = "You have liked this recipe!"
    else
      flash[:danger] = "Sorry, only one vote per recipe!"
    end
    redirect_to :back
  end

  private
    def find_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe).permit(:name, :summary, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<%= form_for @chef do |f| %>
  <div class="form-group">
    <%= f.label :chefname %>
    <%= f.text_field :chefname, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <%= f.submit(@chef.new_record? ? "Register" : "Edit Profile", class: "btn btn-success") %>
<% end %>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit User" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: "All Chefs" %>

<% @chefs.each do |chef| %>
  <%= link_to gravatar_for(chef, size: 200), chef_path(chef) %>
  <%= link_to chef.chefname, chef_path(chef) %><br><hr>
<% end %>

<%= will_paginate %>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Create User" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: "Chef: " + @chef.chefname %>

<div class="row">
  <div class="col-md-4">
    <%= gravatar_for @chef, size: 200 %>
  </div>
  <div class="col-md-4">
    Name: <%= @chef.chefname %><br>
    Email: <%= @chef.email %><br>
    Recipes: <br>
    <div class="well">
      <% @recipes.each do |recipe| %>
        <%= link_to recipe.name, recipe_path(recipe) %><br>
      <% end %>
      <%= will_paginate @recipes %>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="container-fluid">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">
      <hr>
      <p class="pull-left">
        &copy; RecipeManager 2016
      </p>
      <p>
        <%= link_to "Something", "#", class: "pull-right" %>
      </p>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RecipeManager", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Recipes", recipes_path %></li>
        <li><%= link_to "Create Recipe", new_recipe_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
          <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", "" %></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Sign Out", logout_path %></li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "Login", login_path %>
          </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_notifications.html.erb
<div class="row">
  <div class="col-md-offset-1 col-md-10">
    <% flash.each do |alert, msg| %>
    <div class="alert alert-<%= alert %>"><%= msg %>
      <a class="close" data-dismiss="alert">&#215;</a>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipemanager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'layouts/notifications' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: "Login" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_tag '/login' do%>
      <%= label_tag :email %>
      <%= text_field_tag :email %><br>

      <%= label_tag :password %>
      <%= password_field_tag :password %>

      <%= submit_tag "Login", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <div class="center column-flex jumbotron">
        <h1>Welcome</h1>
        <h2>Blah blah blah...</h2>
        <div class="button-group">
          <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %>
          <%= link_to "Login", login_path, class: "btn btn-lg btn-success" %>
          <%= link_to "See All Chefs!", chefs_path, class: "btn btn-lg btn-success" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= render 'shared/errors', obj: @recipe %>

<%= form_for(@recipe, html: { multipart: true }) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_field :summary, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpg,image/gif,image/jpeg,image/png' %><br>
  </span>

  <%= f.submit(@recipe.new_record? ? "Create Recipe" : "Edit Recipe", class: "btn btn-success") %>
<% end %>


<script type="text/javascript">
  $('#recipe_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert("Maximum file size is 5MB. Please choose a smaller file.");
    }
  });
</script>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: "Edit Recipe" %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: "All Recipes" %>

<div class="col-md-offset-4 col-md-4">
  <% @recipes.each do |recipe| %>
  <div class="col-md-2">
    <div class="row">
      <section class="chef_info center">
        <%= gravatar_for recipe.chef, size: 100 %>
        <h5><b>Chef Name: </b><%= link_to recipe.chef.chefname, chef_path(recipe.chef) %></h5>
      </section>
    </div>
  </div>
  <%= image_tag(recipe.picture.url, size: "250x150", class: "recipe-image") if recipe.picture? %>
  <p>
    <b>Name:</b> <%= link_to recipe.name, recipe_path(recipe) %>
  </p>
  <p>
    <b>Summary:</b> <%= recipe.summary %>
  </p>
  <p>
    <b>Description:</b> <%= recipe.description %>
  </p>
  <p>
    <small>Created <%= time_ago_in_words(recipe.created_at) %> ago, updated <%= time_ago_in_words(recipe.updated_at) %> ago...</small>
  </p>
  <br><br>
  <% end %>
  <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: "Create Recipes" %>
<hr>

<div class="col-md-offset-4 col-md-5">
  <div class="well">
    <%= render 'form' %>
  </div>
</div>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>
<div class="row">
  <div class="col-md-offset-4 col-md-4">
    <%= gravatar_for @recipe.chef, size: 200 %>
    <p>
      <b>Created by: </b> <%= @recipe.chef.chefname %>
    </p>
    <h1>Name: <%= @recipe.name %></h1>
    <h2>Summary: <%= @recipe.summary %></h2>
    <h3>Description: <%= simple_format(@recipe.description) %></h3><br>
    <%= image_tag(@recipe.picture.url, class: "gravatar") if @recipe.picture? %>
    <div class="pull-right">
      <%= link_to like_recipe_path(@recipe, like: true), method: :post  do %>
        <i class="glyphicon glyphicon-thumbs-up" ></i>&nbsp; <%= @recipe.thumbs_up_total %>
      <% end %>
        &nbsp;&nbsp;|&nbsp;&nbsp;
      <%= link_to like_recipe_path(@recipe, like: false), method: :post  do %>
        <i class="glyphicon glyphicon-thumbs-down" ></i>&nbsp; <%= @recipe.thumbs_down_total %>
      <% end %>
    </div>
    <% if logged_in? and @recipe.chef == current_user %>
      <%= link_to "Edit", edit_recipe_path, class: "btn btn-success"%>
    <% end %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="alert alert-danger col-md-8 col-md-offset-2">
      <h5>Please correct the following errors:</h5>
      <ul>
        <% obj.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 class="text-center"> <%= title %></h1>
<hr>